const LOG_IN = {
  REQUEST: 'LOG_IN_REQUEST',
  SUCCESS: 'LOG_IN_SUCCESS',
  FAILURE: 'LOG_IN_FAILURE',
};

const LOG_OUT = {
  REQUEST: 'LOG_OUT_REQUEST',
  SUCCESS: 'LOG_OUT_SUCCESS',
  FAILURE: 'LOG_OUT_FAILURE',
};

export { LOG_IN, LOG_OUT };
